### ISSUE TITLE
Transpile es build to ES5

### ISSUE THREAD

**Issue by johannes-z** [znck/vue-runtime-helpers#8]
The ES build should not have to be transpiled by consuming apps/libs.

Changing the `target` inside [tsconfig.json](https://github.com/znck/vue-runtime-helpers/blob/master/tsconfig.json#L5) to `es5` should be enough.

Also see: https://github.com/rollup/plugins/tree/master/packages/babel#external-dependencies

> We encourage library authors not to distribute code that uses untranspiled ES6 features (other than modules) for this reason. Consumers of your library should not have to transpile your ES6 code, any more than they should have to transpile your CoffeeScript, ClojureScript or TypeScript.

I can create a PR if you want me to.

**Comment by znck** [comment]
Accepting PR
